name: "BetterBlockBreaking"
main: com.github.cheesesoftware.betterblockbreaking.BetterBlockBreaking
version: "${version}"
depend: [ProtocolLib]
softdepend: [WorldGuard, Slimefun]
api-version: "1.16"
author: "gustav9797"
authors:
  - SamB440
  - DrkMatr1984
